name = "Fabulously Optimized"
author = "robotkoer"
version = "12.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b15ac45ef77793898b3b9fb5b0c49332fc9153ff48cd756f95583e803bd0b27"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
