name = "Fabulously Optimized"
author = "robotkoer"
version = "12.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44f96ee69fea0616886898bc8c5477ff9e71dfaf6eef4012a315416d83159987"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
