hash-format = "sha256"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/be_by.json"
hash = "db87c9322336f3ef307fee2ba2773bb4cda4fc91177efc83748463e5292870c3"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/en_us.json"
hash = "bbf8b1ac1a331cddc08aa5b75ca03c7f213abc5292a2b586858d4440efb03d56"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/es_es.json"
hash = "aba3eafe1f0ca97987926874250c65b68c4dff810b6ec83b6367e56c47cd7a3f"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/es_ve.json"
hash = "aba3eafe1f0ca97987926874250c65b68c4dff810b6ec83b6367e56c47cd7a3f"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/et_ee.json"
hash = "4c7735ab8cf4a7f410f52941569f9b90dbd9a73ec63b4d72de156e99fedef129"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/fr_fr.json"
hash = "843e10d26a04448cc21dce3f7ae09aa94d5d7948d6274d44287026ef905d7eca"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/he_il.json"
hash = "05503e802d5b950f3c944154eabb1a20f68cdb1337cf52dbd1bc4c3dfd09e936"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/it_it.json"
hash = "2dd6802de6615175c3ea9cb148d826d0fad0d50f1d2571ed2f38ad92e7507f48"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/ms_my.json"
hash = "d7722504bfdadf3ccab222686d4493313e432ef46b9c713d9a58f9d813228b26"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/pl_pl.json"
hash = "38bd3b9fd0cd37f0941f450e0cb0b1c8b5ede46a2a02f4d168792d1fe692f9a0"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/ro_ro.json"
hash = "f2f5dd32c2b0c905fd9dbee03dccfab71ddc4df9cda7c39b93672d3df30579e6"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/ru_ru.json"
hash = "79811c73d059146b7b97b7d853565540aac3ea5cc7cefa237f2927dde1a2e242"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/vi_vn.json"
hash = "d6085babb8bd3735c3cd947f54f6c4ec9756a2548b49427270b82b87d3b525df"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/zh_cn.json"
hash = "03fed9b3e4d04110e0770f73225a2ae9ba698330d5a12cab461f545651e8f94e"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/zh_tw.json"
hash = "d0a3705b15eacc96e4b4a78265a89beff57667126d319a4d58f3ec8610b8fb48"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/zlm_arab.json"
hash = "5b513e3db40b4fd9fc62e8bda26abfcb8a786f8d7a32478465f540e0db4710f1"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "de3af8e716eff548f2e754f8f3b6b9ab6bb2a7eea674f926855205e0f33411b1"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "c37294a4fb07a4ccf555e1ca3eb979def0d116e0f44389424f0e9c2ab6b063fb"

[[files]]
file = "config/modpack_defaults/config/NoChatReports/NCR-Client.json"
hash = "616e09c8ff849f4a9a07165a0a3513f468469237377546b64135591fca8a0592"

[[files]]
file = "config/modpack_defaults/config/NoChatReports/NCR-Common.json"
hash = "c335cb5e65abce1bfc063eaddcff3eca759636e32ba7e4993ea249a31ab18816"

[[files]]
file = "config/modpack_defaults/config/PaginatedAdvancements.json5"
hash = "3a1c71d2011cac176e00697237148ee882393b19394374862f8025f129d4c5a2"

[[files]]
file = "config/modpack_defaults/config/bettergrass.json"
hash = "8aaf74864043e08741cc3c60f3ffe0d9aaf1fe757f111bb41064fb580d25bdf1"

[[files]]
file = "config/modpack_defaults/config/capes.json5"
hash = "69de1a523d9ca24248233c11178b2492984ba0b25b0355242d72b2ae17a7c284"

[[files]]
file = "config/modpack_defaults/config/citresewn.json"
hash = "057e9e53790394db8b700616de3c235b0af3dc12fe7731a66ad20026acb9d991"

[[files]]
file = "config/modpack_defaults/config/crash_assistant/config.toml"
hash = "f6e7fd1a6ada739da42d8cb8395232b28595fb7b74fc3c990d1947a3ef3a79cc"

[[files]]
file = "config/modpack_defaults/config/crash_assistant/crash_assistant_localization_overrides/be_by.json"
hash = "db87c9322336f3ef307fee2ba2773bb4cda4fc91177efc83748463e5292870c3"

[[files]]
file = "config/modpack_defaults/config/crash_assistant/crash_assistant_localization_overrides/en_us.json"
hash = "bbf8b1ac1a331cddc08aa5b75ca03c7f213abc5292a2b586858d4440efb03d56"

[[files]]
file = "config/modpack_defaults/config/crash_assistant/crash_assistant_localization_overrides/es_es.json"
hash = "aba3eafe1f0ca97987926874250c65b68c4dff810b6ec83b6367e56c47cd7a3f"

[[files]]
file = "config/modpack_defaults/config/crash_assistant/crash_assistant_localization_overrides/es_ve.json"
hash = "aba3eafe1f0ca97987926874250c65b68c4dff810b6ec83b6367e56c47cd7a3f"

[[files]]
file = "config/modpack_defaults/config/crash_assistant/crash_assistant_localization_overrides/et_ee.json"
hash = "4c7735ab8cf4a7f410f52941569f9b90dbd9a73ec63b4d72de156e99fedef129"

[[files]]
file = "config/modpack_defaults/config/crash_assistant/crash_assistant_localization_overrides/fr_fr.json"
hash = "843e10d26a04448cc21dce3f7ae09aa94d5d7948d6274d44287026ef905d7eca"

[[files]]
file = "config/modpack_defaults/config/crash_assistant/crash_assistant_localization_overrides/he_il.json"
hash = "05503e802d5b950f3c944154eabb1a20f68cdb1337cf52dbd1bc4c3dfd09e936"

[[files]]
file = "config/modpack_defaults/config/crash_assistant/crash_assistant_localization_overrides/it_it.json"
hash = "2dd6802de6615175c3ea9cb148d826d0fad0d50f1d2571ed2f38ad92e7507f48"

[[files]]
file = "config/modpack_defaults/config/crash_assistant/crash_assistant_localization_overrides/ms_my.json"
hash = "d7722504bfdadf3ccab222686d4493313e432ef46b9c713d9a58f9d813228b26"

[[files]]
file = "config/modpack_defaults/config/crash_assistant/crash_assistant_localization_overrides/pl_pl.json"
hash = "38bd3b9fd0cd37f0941f450e0cb0b1c8b5ede46a2a02f4d168792d1fe692f9a0"

[[files]]
file = "config/modpack_defaults/config/crash_assistant/crash_assistant_localization_overrides/ro_ro.json"
hash = "f2f5dd32c2b0c905fd9dbee03dccfab71ddc4df9cda7c39b93672d3df30579e6"

[[files]]
file = "config/modpack_defaults/config/crash_assistant/crash_assistant_localization_overrides/ru_ru.json"
hash = "79811c73d059146b7b97b7d853565540aac3ea5cc7cefa237f2927dde1a2e242"

[[files]]
file = "config/modpack_defaults/config/crash_assistant/crash_assistant_localization_overrides/vi_vn.json"
hash = "d6085babb8bd3735c3cd947f54f6c4ec9756a2548b49427270b82b87d3b525df"

[[files]]
file = "config/modpack_defaults/config/crash_assistant/crash_assistant_localization_overrides/zh_cn.json"
hash = "03fed9b3e4d04110e0770f73225a2ae9ba698330d5a12cab461f545651e8f94e"

[[files]]
file = "config/modpack_defaults/config/crash_assistant/crash_assistant_localization_overrides/zh_tw.json"
hash = "d0a3705b15eacc96e4b4a78265a89beff57667126d319a4d58f3ec8610b8fb48"

[[files]]
file = "config/modpack_defaults/config/crash_assistant/crash_assistant_localization_overrides/zlm_arab.json"
hash = "5b513e3db40b4fd9fc62e8bda26abfcb8a786f8d7a32478465f540e0db4710f1"

[[files]]
file = "config/modpack_defaults/config/debugify.json"
hash = "375d545e83e1aabc7700c5f0bea4f7bcf1a19e5e35f9a2155bde2e1c9b0ebc61"

[[files]]
file = "config/modpack_defaults/config/dynamic_fps.json"
hash = "f773c03c1cce5797e4d4698939ba8a06f421101a0403b8e018c3f3d86e752a45"

[[files]]
file = "config/modpack_defaults/config/entity_texture_features.json"
hash = "6a3760d2b7828efc524976294cc6fd17f16bdda9d9827bd55f8fcd58ce724355"

[[files]]
file = "config/modpack_defaults/config/fabric_loader_dependencies.json"
hash = "de3af8e716eff548f2e754f8f3b6b9ab6bb2a7eea674f926855205e0f33411b1"

[[files]]
file = "config/modpack_defaults/config/fabrishot.properties"
hash = "f5ff731194f66727bfeb75a28a70104fc4687cbc84b69e60c94fe1b7d901f453"

[[files]]
file = "config/modpack_defaults/config/fastquit.toml"
hash = "17225e085e6759210cec7e829e00c8c90f9c5d38714835cb5da9c98398842f7d"

[[files]]
file = "config/modpack_defaults/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/modpack_defaults/config/isxander-main-menu-credits.json"
hash = "c37294a4fb07a4ccf555e1ca3eb979def0d116e0f44389424f0e9c2ab6b063fb"

[[files]]
file = "config/modpack_defaults/config/lambdynlights.toml"
hash = "326ec0c840e65aedf5c6048ea6016d551be38cf23f692949e105a4a388ad8be7"

[[files]]
file = "config/modpack_defaults/config/midnightlib.json"
hash = "57b848fb6d7c03b6124297de49b1e4cb169e74db042c74aecf79f035ae2f3980"

[[files]]
file = "config/modpack_defaults/config/modernfix-mixins.properties"
hash = "ff2fb838e13e529a5939896a0775595c2e0c9d1288c7afca76ff1d3fd5646c97"

[[files]]
file = "config/modpack_defaults/config/modmenu.json"
hash = "b7b9cdc1e99bdfd86052e373dc3e0ae87c73760816454b801b09d0cfd7b79604"

[[files]]
file = "config/modpack_defaults/config/moreculling.toml"
hash = "60eb0902eac918d39fb5eb7df66314f5748aef0259b4ad5bdeacd27dfff120ca"

[[files]]
file = "config/modpack_defaults/config/puzzle.json"
hash = "4449fb9b3440c4367f861d0f8e75b879caf6c897cb47569f13929ca37d6c864d"

[[files]]
file = "config/modpack_defaults/config/rrls.toml"
hash = "3630be880dc7f037238b7e6347201d4f716ffc7e16db0a1498ef2f775cf8f5be"

[[files]]
file = "config/modpack_defaults/config/sodium-extra-options.json"
hash = "6c02a3834146f91beeb4baa7a25abdfbbe7a9879ed53399465c17f7f61924801"

[[files]]
file = "config/modpack_defaults/config/sodium-options.json"
hash = "37aaf52aa7545527c7ade71ac77ad2fcf6019995bf58b6ea1fe0f52949919d18"

[[files]]
file = "config/modpack_defaults/config/sodium-shadowy-path-blocks-options.json"
hash = "4773ede8076bdbcfb6b8ea3de058a56120aa7438ee6b25de297c10aa8f5ce393"

[[files]]
file = "config/modpack_defaults/options.txt"
hash = "edd18730edde6d07394ca0631b03a8ea4dbe65294f4f13e42152a71ddb3645de"

[[files]]
file = "mods/animatica.pw.toml"
hash = "23b3d1ad268ba3a1eaaea01b74ff3dd5ae9123c0cb0ba29ec85c98b0e6eadfba"
metafile = true

[[files]]
file = "mods/bettergrass.pw.toml"
hash = "6a4438861eb234be921396599e8ea655b404ac20c20e03a8a40432ab414c706b"
metafile = true

[[files]]
file = "mods/bettermounthud.pw.toml"
hash = "24b0177dacb547321d83487699e13bf6f6fa004c0d8199dbcc0867b2c21097ee"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "d7384472a7c1c58b70d0b27e3681f79082e87150402c8bab4eda8e77a8209a7a"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "91ec280bb0b40533a4f43601f074eb0d3ff52a606cd0a3b700802b228670f4ef"
metafile = true

[[files]]
file = "mods/config_manager.pw.toml"
hash = "656140ce02ed1d7fe53773b81cc09bc804d77d09c55a9b9d734785e9cf4b8743"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "59060a934906e4cbd6a19b91ab63e40761de5699166366bf2e0e6d2062aec539"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "32b5f79a6b49454201e08ad2dc280653de8388779b886ceae8799f9913cf304b"
metafile = true

[[files]]
file = "mods/crash_assistant.pw.toml"
hash = "9c405776e3930b199e9cb5447d685b0a537a20e0f56dac193c6652313b6f7888"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "867f8e4be9bc139a517dbcf55aefc2938c5e461640bd08024ec4716fce068025"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "40cd28ee0012a938d0bd8dedf94f44bc7890d69c6a824597197e30f26f8b229e"
metafile = true

[[files]]
file = "mods/dynamic_fps.pw.toml"
hash = "eb6eec0ac2a41cae603413b9216d1c42dd5bf588e1d45a696e4e003f7222490e"
metafile = true

[[files]]
file = "mods/e4mc.pw.toml"
hash = "f9f1e8581fa017b5db68c9183e020083ed2bdcd5b415346aa22aa77cae34583b"
metafile = true

[[files]]
file = "mods/entity_model_features.pw.toml"
hash = "3839761576edb967af437a8b5dc8fb6868996a6accc6a1ac666e15348e6b5372"
metafile = true

[[files]]
file = "mods/entity_texture_features.pw.toml"
hash = "3cf152840330722a119ba90ac8f2c614eebf5e37460e0a5c0db96b10442d861e"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "9d62264174b60141a12bda075ba08569ee0d8a96074f052231feea874fdd9ffe"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "08a7da23c3533ff859cfbe0660630b2bce51e26b03a95ba4654a6184bf28a428"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "1b09260a38cc12b117bc9f63083a581d0e1a158ae941c6533c45f769f4489004"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "1bbacf4844881b1367ff761b3ce1c5cc7ef61eb6514d3a7f41cc994e43cc57da"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "cbeb9402a1014268ead085555ddc841281ec08101d9df27fb9aa7d1d91cae79c"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "12688b92bc20fdcf28bb02328c2d632f7df8312f577d953bb459dbb4e14f01a0"
metafile = true

[[files]]
file = "mods/forgeconfigapiport.pw.toml"
hash = "59763290be9efedece6960fa2d4afb42cd10776a9ed73ceec786391154462947"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "5ed7272b0b4060e5ee01cbe6984638cf5bdc4b61a8419003a055c04e9ca7cc3e"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "f871de4d57dbdf4e5ad512ec21f1e9baa3a6ff1596399ac57a758a1c26b2418e"
metafile = true

[[files]]
file = "mods/isxander-main-menu-credits.pw.toml"
hash = "21843e75802603fc737c7599bbd6550e85d77e882e9b0aa5df279ae1270392d6"
metafile = true

[[files]]
file = "mods/lambdynlights.pw.toml"
hash = "a4d49814dd3f38c133ca49ed66de88234c69578a3f586c0434d1b6502d6d31de"
metafile = true

[[files]]
file = "mods/languagereload.pw.toml"
hash = "c575ad32315d38916df9a7148afb4d05430a40869074c1e87dc61873f5a77747"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "186ff3d734f9d6718daa6e8242884d69be59f4d1d0b0eb95a1140934e497289b"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "0a8e6a58962ba40f696a44cb2d02355490bc831b49509f8083e3e7bc89b40052"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "20853b64aec9d938a92a6b3b45158b67159f16bd2c08b659aea6e29df23d3be1"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "9dba1fb1be6e3876cc3fb52831957a0aab142cf5ab8c688d55aee8921855de01"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "c3d0746be98e5f5eaf1731a84e84724289f45f6b49836c5106e8d4669d3f84ec"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "6006fa2a1c9e1ecb4faf424b2a4c0086ad18077f6cc22c0d25fe59f1d3839900"
metafile = true

[[files]]
file = "mods/nochatreports.pw.toml"
hash = "e01e4e296bff245a222574cb664cdf07d934356c0de81c6a9ac32a1c9bd25cb2"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "f5273d4065ede04639ac6796cac0420d6cafed743a930a8f2c70f6f9c37e7bf3"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "cbe531f3cb8cd726ba811e3f8c4803ee7c3485be0ed6fce91908aa80a55c907e"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "78edf00f2118746d8653541d5a9dbac5c064bc69d8e43a99edc0a20e97d7fb74"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "983290f26e4e746fcccfcd6701b0afe547e2c01952d3560625c1e996c751c10c"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "b039f55985a83e7ed5f5004a21ee3d0faa5f566ee5c8b595718febfc3e4a75e5"
metafile = true

[[files]]
file = "mods/skyboxify.pw.toml"
hash = "9aa7a57232681724c66dfcc86fedb1d3bfe86f12e44bb654f833fd12806f45da"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "146ad722eecbf7bc624c86e4f03b10fb05a139f9910cf67cb3262101bf9787e4"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "1b05c3d841542fdce7815a7fcef89e73f01a754943f292cb1e81e047cb3db362"
metafile = true

[[files]]
file = "mods/sspb.pw.toml"
hash = "9a7b77d36b9aba3015e540205750b0bc64223afee043a7146708e26d1e501af9"
metafile = true

[[files]]
file = "mods/yet_another_config_lib_v3.pw.toml"
hash = "9047468f7e046a63cbd1a18d78cbfc246a4f853777c719c02415bf0209aada2f"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "84f11b2ec4d6aa8ea3545d161e29296be076eb4488c458e4311e4a9d33a6e6f5"
metafile = true

[[files]]
file = "resourcepacks/Chat_Reporting_Helper.pw.toml"
hash = "2d0fa08197a563fe705757891381c8e4fee1a229e184cffd58e390de3d293040"
metafile = true

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "85d770b75fd01873095e46a4e15f8dc4f82318ceda16bb1b674375c7cde9ebb6"

[[files]]
file = "resourcepacks/Translations_for_Sodium.pw.toml"
hash = "b1d480380d17df572c68a644835c24d68a00a634cde10bae7147595103794fab"
metafile = true
